apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alchemorsel-staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml
  - ingress-patch.yaml

images:
  - name: ghcr.io/alchemorsel/v3
    newTag: staging-latest
  - name: ghcr.io/alchemorsel/v3-web
    newTag: staging-latest

commonLabels:
  environment: staging
  version: v3

configMapGenerator:
  - name: alchemorsel-config
    literals:
      - environment=staging
      - log_level=debug
      - ollama_url=http://alchemorsel-ollama:11434
      - otel_endpoint=http://otel-collector:4317
      - max_upload_size=5MB
      - rate_limit=100
      - cache_ttl=300

secretGenerator:
  - name: alchemorsel-secrets
    type: Opaque
    options:
      disableNameSuffixHash: true
    files:
      - database-url=secrets/staging-database-url
      - redis-url=secrets/staging-redis-url
      - jwt-secret=secrets/staging-jwt-secret

replicas:
  - name: alchemorsel-api
    count: 2
  - name: alchemorsel-web
    count: 1
  - name: alchemorsel-ollama
    count: 1

nameSuffix: -staging