version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: alchemorsel-postgres-dev
    environment:
      POSTGRES_DB: alchemorsel_dev
      POSTGRES_USER: alchemorsel
      POSTGRES_PASSWORD: alchemorsel_dev_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/infrastructure/persistence/migrations/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alchemorsel -d alchemorsel_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: alchemorsel-redis-dev
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
    driver: local