apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alchemorsel

resources:
  - ../../base
  - pvc.yaml
  - blue-green-service.yaml
  - canary-service.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml
  - ingress-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: alchemorsel-api
    path: deployment-security-patch.yaml

images:
  - name: ghcr.io/alchemorsel/v3
    newTag: production-latest
  - name: ghcr.io/alchemorsel/v3-web
    newTag: production-latest

commonLabels:
  environment: production
  version: v3

configMapGenerator:
  - name: alchemorsel-config
    literals:
      - environment=production
      - log_level=info
      - ollama_url=http://alchemorsel-ollama:11434
      - otel_endpoint=http://otel-collector:4317
      - max_upload_size=10MB
      - rate_limit=1000
      - cache_ttl=3600

secretGenerator:
  - name: alchemorsel-secrets
    type: Opaque
    options:
      disableNameSuffixHash: true
    files:
      - database-url=secrets/database-url
      - redis-url=secrets/redis-url
      - jwt-secret=secrets/jwt-secret
      - ssl-cert=secrets/ssl-cert.pem
      - ssl-key=secrets/ssl-key.pem

replicas:
  - name: alchemorsel-api
    count: 6
  - name: alchemorsel-web
    count: 3
  - name: alchemorsel-ollama
    count: 1