version: '3.8'

services:
  # Elasticsearch - Data storage and search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: alchemorsel-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=alchemorsel-logs
      - node.name=elasticsearch-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - xpack.security.authc.anonymous.roles=superuser
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.monitoring.collection.enabled=true
      - action.destructive_requires_name=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

  # Logstash - Log processing and transformation
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.3
    container_name: alchemorsel-logstash
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
      - MONITORING_ENABLED=false
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/patterns:/usr/share/logstash/patterns:ro
      - ./logstash/templates:/usr/share/logstash/templates:ro
    ports:
      - "5044:5044"    # Beats input
      - "5000:5000"    # TCP input
      - "9600:9600"    # Logstash monitoring API
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

  # Kibana - Data visualization and exploration
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: alchemorsel-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana.alchemorsel.com
      - SERVER_BASEPATH=/kibana
      - XPACK_MONITORING_ENABLED=true
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=a7a6311933d3503b89bc2dbc36572c33a7a6311933d3503b89bc2dbc36572c33
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

  # Filebeat - Log collection from containers
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.3
    container_name: alchemorsel-filebeat
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LOGSTASH_HOSTS=logstash:5044
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat_data:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - /home/hermes/alchemorsel-v3/logs:/app/logs:ro
    depends_on:
      logstash:
        condition: service_healthy
    networks:
      - elk

  # Metricbeat - System and service metrics
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.11.3
    container_name: alchemorsel-metricbeat
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - metricbeat_data:/usr/share/metricbeat/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk

  # Heartbeat - Uptime monitoring
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.11.3
    container_name: alchemorsel-heartbeat
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - heartbeat_data:/usr/share/heartbeat/data
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk

  # Curator - Index lifecycle management
  curator:
    image: untergeek/curator:8.0.9
    container_name: alchemorsel-curator
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ./curator/config:/usr/share/curator/config:ro
      - ./curator/actions:/usr/share/curator/actions:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
    # Run curator daily at 2 AM
    command: >
      sh -c "
        echo '0 2 * * * curator --config /usr/share/curator/config/curator.yml /usr/share/curator/actions/cleanup.yml' | crontab -
        && crond -f
      "

volumes:
  elasticsearch_data:
    driver: local
  filebeat_data:
    driver: local
  metricbeat_data:
    driver: local
  heartbeat_data:
    driver: local

networks:
  elk:
    driver: bridge
    external: false