apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: "2.40.0"
      timeInterval: "5s"
      queryTimeout: "60s"
      cacheLevel: "Medium"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
    
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger-query-service:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - key: service.name
            value: job
        filterByTraceID: false
        filterBySpanID: false
        mapTagNamesEnabled: false
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
      
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "TraceID"
          label: "trace_id"
          url: "http://jaeger-query-service:16686/trace/$${__value.raw}"
          datasourceUid: jaeger
        - name: "RequestID"
          label: "request_id"
          url: ""
          datasourceUid: ""

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: keys
      defaultRegion: us-east-1
      customMetricsNamespaces: "AWS/EKS,AWS/ApplicationELB,AWS/RDS,AWS/ElastiCache"
    secureJsonData:
      accessKey: "${AWS_ACCESS_KEY_ID}"
      secretKey: "${AWS_SECRET_ACCESS_KEY}"

  - name: PostgreSQL
    type: postgres
    url: postgres-service:5432
    database: alchemorsel
    user: grafana_reader
    secureJsonData:
      password: "${POSTGRES_GRAFANA_PASSWORD}"
    jsonData:
      sslmode: require
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-service:6379
    secureJsonData:
      password: "${REDIS_PASSWORD}"
    jsonData:
      client: "cluster"
      poolSize: 5
      timeout: 10
      pingInterval: 0

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "alchemorsel-logs-*"
    jsonData:
      esVersion: "8.0.0"
      includeFrozen: false
      interval: "Daily"
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
    
  - name: TestData
    type: testdata
    uid: testdata
    access: proxy
    isDefault: false